insert into etiquettes (id, nom) values (1, 'habitasse platea dictumst');
insert into etiquettes (id, nom) values (2, 'at turpis');
insert into etiquettes (id, nom) values (3, 'nisl');
insert into etiquettes (id, nom) values (4, 'nibh');
insert into etiquettes (id, nom) values (5, 'eget eros');
insert into etiquettes (id, nom) values (6, 'et');
insert into etiquettes (id, nom) values (7, 'pede');
insert into etiquettes (id, nom) values (8, 'lectus pellentesque at');
insert into etiquettes (id, nom) values (9, 'faucibus orci luctus');
insert into etiquettes (id, nom) values (10, 'luctus tincidunt nulla');
insert into etiquettes (id, nom) values (11, 'sollicitudin ut');
insert into etiquettes (id, nom) values (12, 'imperdiet et');
insert into etiquettes (id, nom) values (13, 'ut');
insert into etiquettes (id, nom) values (14, 'magna vestibulum');
insert into etiquettes (id, nom) values (15, 'risus');
insert into etiquettes (id, nom) values (16, 'luctus');
insert into etiquettes (id, nom) values (17, 'rhoncus sed');
insert into etiquettes (id, nom) values (18, 'nullam sit amet');
insert into etiquettes (id, nom) values (19, 'enim lorem');
insert into etiquettes (id, nom) values (20, 'curabitur in');
